"""
Markdown日記ライター

要約結果をMarkdown形式の日記ファイルとして出力。
"""

from datetime import datetime
from pathlib import Path


DIARY_TEMPLATE = """# 開発日記: {date}

## 📝 Summary

{summary}

---

## 📁 File Changes

{file_changes}

---

## 🎯 Decisions

{decisions}

---

## 💡 Learnings

{learnings}

---

## ➡️ Next Steps

{next_steps}

---

*Generated by dev-diary tool*
"""


def write_diary(
    summary: dict,
    output_dir: str | Path,
    date: datetime | None = None
) -> Path:
    """
    日記Markdownファイルを出力
    
    Args:
        summary: summarizer.pyから取得したDiarySummary
        output_dir: 出力先ディレクトリ
        date: 日付（Noneの場合は今日）
        
    Returns:
        作成したファイルのパス
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    date = date or datetime.now()
    filename = date.strftime("%Y-%m-%d.md")
    filepath = output_dir / filename
    
    content = DIARY_TEMPLATE.format(
        date=date.strftime("%Y-%m-%d (%a)"),
        summary=summary.get("summary", "No summary available"),
        file_changes=_format_list(summary.get("file_changes", [])),
        decisions=_format_list(summary.get("decisions", [])),
        learnings=_format_list(summary.get("learnings", [])),
        next_steps=_format_list(summary.get("next_steps", []))
    )
    
    filepath.write_text(content, encoding="utf-8")
    return filepath


def _format_list(items: list[str]) -> str:
    """箇条書きリストに変換"""
    if not items:
        return "- (None)"
    return "\n".join(f"- {item}" for item in items)
